/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.46
 * Generated at: 2025-10-04 22:17:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.0.jar", Long.valueOf(1759616237429L));
    _jspx_dependants.put("jar:file:/C:/Users/slevi/Downloads/FinanceWebApp/build/web/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.0.jar!/META-INF/c.tld", Long.valueOf(1649416098000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <title>Wealthory - FMS</title>\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" href=\"images/sm-logo.png\" sizes=\"32x32\">\n");
      out.write("        <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body class=\"bg-white min-h-screen\">\n");
      out.write("\n");
      out.write("        <!-- Navbar -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "components/navbar.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("        <!-- Hero Section -->\n");
      out.write("        <section class=\"pt-40 pb-20 px-4 text-center\">\n");
      out.write("            <div class=\"container mx-auto\">\n");
      out.write("                <h1 class=\"text-3xl md:text-6xl pb-6 font-bold text-teal-700\">\n");
      out.write("                    Manage Your Everyday Finances <br/> with Intelligence\n");
      out.write("                </h1>\n");
      out.write("                <p class=\"text-sm text-gray-600 mb-8 md:text-xl\">\n");
      out.write("                    Smarter money management with AI <br/> track, analyze, and optimize your finances in real time.\n");
      out.write("                </p>\n");
      out.write("                <div class=\"flex justify-center space-x-4\">\n");
      out.write("                    <a href=\"dashboard.jsp\">\n");
      out.write("                        <button class=\"px-8 py-2 bg-teal-700 text-white rounded-lg hover:bg-teal-800\">\n");
      out.write("                            Get Started\n");
      out.write("                        </button>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mt-5 md:mt-3\">\n");
      out.write("                    <img src=\"images/hero-banner.jpeg\" alt=\"Dashboard Preview\" \n");
      out.write("                         class=\"rounded-lg shadow-2xl border mx-auto\" />\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <!-- Stats Section -->\n");
      out.write("        <section id=\"stats\" class=\"py-10 bg-blue-50 m-5 font-sans\">\n");
      out.write("            <div class=\"mx-auto px-4\">\n");
      out.write("                <h2 class=\"text-3xl font-bold text-center mb-12\">Here our Stats</h2>\n");
      out.write("                <div class=\"grid grid-cols-2 md:grid-cols-4 gap-6 md:gap-8 text-center\">\n");
      out.write("                    <div class=\"p-4 bg-white rounded shadow hover:bg-gray-100\">\n");
      out.write("                        <div class=\"text-xl md:text-4xl font-bold text-blue-600 mb-2\">75K+</div>\n");
      out.write("                        <div class=\"text-gray-600 text-sm md:text-xl\">Users Onboarded</div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"p-4 bg-white rounded shadow hover:bg-gray-100\">\n");
      out.write("                        <div class=\"text-xl md:text-4xl font-bold text-blue-600 mb-2\">$3.1B+</div>\n");
      out.write("                        <div class=\"text-gray-600 text-sm md:text-xl\">Financial Activity Tracked</div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"p-4 bg-white rounded shadow hover:bg-gray-100\">\n");
      out.write("                        <div class=\"text-xl md:text-4xl font-bold text-blue-600 mb-2\">99.99%</div>\n");
      out.write("                        <div class=\"text-gray-600 text-sm md:text-xl\">System Availability</div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"p-4 bg-white rounded shadow hover:bg-gray-100\">\n");
      out.write("                        <div class=\"text-xl md:text-4xl font-bold text-blue-600 mb-2\">4.8/5</div>\n");
      out.write("                        <div class=\"text-gray-600 text-sm md:text-xl\">Customer Satisfaction</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <!-- Features Section -->\n");
      out.write("        <section id=\"features\" class=\"py-16 px-4 bg-gradient-to-br from-blue-50 via-cyan-50 to-indigo-100\">\n");
      out.write("            <div class=\"container mx-auto max-w-7xl\">\n");
      out.write("                <h2 class=\"text-4xl font-extrabold text-center mb-12 text-transparent bg-clip-text bg-gradient-to-r from-teal-700 via-blue-700 to-indigo-700\">\n");
      out.write("                    Everything you need to manage your finances\n");
      out.write("                </h2>\n");
      out.write("                <div class=\"grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-10\">\n");
      out.write("                    <!-- Feature Card -->\n");
      out.write("                    <div class=\"p-8 bg-white/80 backdrop-blur-lg rounded-xl shadow-2xl hover:scale-105 transition text-center border-t-4 border-teal-400\">\n");
      out.write("                        <div class=\"mx-auto mb-5 w-16 h-16 flex items-center justify-center rounded-full bg-gradient-to-tr from-teal-300 via-blue-400 to-indigo-200 shadow-inner text-4xl\">\n");
      out.write("                            📊\n");
      out.write("                        </div>\n");
      out.write("                        <h3 class=\"text-xl font-bold text-teal-700 mb-3\">Real-Time Metrics</h3>\n");
      out.write("                        <p class=\"text-gray-600\">Visualize your cash flow with dynamic graphs powered by AI-backed trends.</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"p-8 bg-white/80 backdrop-blur-lg rounded-xl shadow-2xl hover:scale-105 transition text-center border-t-4 border-blue-400\">\n");
      out.write("                        <div class=\"mx-auto mb-5 w-16 h-16 flex items-center justify-center rounded-full bg-gradient-to-tr from-indigo-200 via-blue-300 to-teal-300 shadow-inner text-4xl\">\n");
      out.write("                            🧾\n");
      out.write("                        </div>\n");
      out.write("                        <h3 class=\"text-xl font-bold text-blue-700 mb-3\">Auto Receipt Capture</h3>\n");
      out.write("                        <p class=\"text-gray-600\">Upload receipts and let our system extract key info instantly and securely.</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"p-8 bg-white/80 backdrop-blur-lg rounded-xl shadow-2xl hover:scale-105 transition text-center border-t-4 border-indigo-400\">\n");
      out.write("                        <div class=\"mx-auto mb-5 w-16 h-16 flex items-center justify-center rounded-full bg-gradient-to-tr from-indigo-200 via-violet-300 to-blue-300 shadow-inner text-4xl\">\n");
      out.write("                            🥧\n");
      out.write("                        </div>\n");
      out.write("                        <h3 class=\"text-xl font-bold text-indigo-700 mb-3\">Smart Budgeting</h3>\n");
      out.write("                        <p class=\"text-gray-600\">Build budgets with smart forecasts and real-time goal tracking.</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"p-8 bg-white/80 backdrop-blur-lg rounded-xl shadow-2xl hover:scale-105 transition text-center border-t-4 border-teal-400\">\n");
      out.write("                        <div class=\"mx-auto mb-5 w-16 h-16 flex items-center justify-center rounded-full bg-gradient-to-tr from-teal-200 via-blue-300 to-indigo-300 shadow-inner text-4xl\">\n");
      out.write("                            💳\n");
      out.write("                        </div>\n");
      out.write("                        <h3 class=\"text-xl font-bold text-teal-700 mb-3\">Unified Account Access</h3>\n");
      out.write("                        <p class=\"text-gray-600\">Link multiple bank accounts and cards with seamless switching.</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"p-8 bg-white/80 backdrop-blur-lg rounded-xl shadow-2xl hover:scale-105 transition text-center border-t-4 border-blue-400\">\n");
      out.write("                        <div class=\"mx-auto mb-5 w-16 h-16 flex items-center justify-center rounded-full bg-gradient-to-tr from-blue-200 via-teal-300 to-indigo-300 shadow-inner text-4xl\">\n");
      out.write("                            🌐\n");
      out.write("                        </div>\n");
      out.write("                        <h3 class=\"text-xl font-bold text-blue-700 mb-3\">Currency Intelligence</h3>\n");
      out.write("                        <p class=\"text-gray-600\">Handle global transactions with built-in currency conversion tools.</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"p-8 bg-white/80 backdrop-blur-lg rounded-xl shadow-2xl hover:scale-105 transition text-center border-t-4 border-indigo-400\">\n");
      out.write("                        <div class=\"mx-auto mb-5 w-16 h-16 flex items-center justify-center rounded-full bg-gradient-to-tr from-indigo-200 via-blue-300 to-teal-300 shadow-inner text-4xl\">\n");
      out.write("                            ⚡\n");
      out.write("                        </div>\n");
      out.write("                        <h3 class=\"text-xl font-bold text-indigo-700 mb-3\">Insight Automation</h3>\n");
      out.write("                        <p class=\"text-gray-600\">Receive proactive financial tips tailored to your habits and goals.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <!-- Footer -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "components/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
